<a href="https://colab.research.google.com/github/ParusSlava/DTA_2026/blob/main/homework/22_05_26_oksana_numpy_homework.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 🏠 Домашнє завдання — NumPy

**До тьюторіалу:** Pandas + Matplotlib: Аналіз даних з нуля

---
### Правила виконання
- Кожне завдання виконуй в окремій клітинці
- Не використовуй цикли там де можна обійтись операціями NumPy
- Після виконання — запусти клітинку і перевір що результат виглядає правильно
- Якщо застряг — поверніться до відповідного розділу тьюторіалу

**Оцінювання:** кожне завдання — 1 бал. Фінальний проєкт — 3 бали. Всього: **14 балів**

---

## Розділ 1 — Масиви ndarray та атрибути

> **Що повторюємо:** `np.array()`, `np.zeros()`, `np.ones()`, `np.arange()`, `np.linspace()`,
> атрибути `.shape`, `.ndim`, `.size`, `.dtype`

### ✏️ Завдання 1.1

У тебе є дані середньомісячних температур у Харкові за рік (°C):

```
-5, -4, 2, 10, 17, 21, 23, 22, 16, 9, 2, -3
```

1. Створи NumPy масив із цих значень і назви його `temps`
2. Виведи масив
3. Виведи: кількість вимірів (`ndim`), форму (`shape`), кількість елементів (`size`), тип даних (`dtype`)
4. Виведи мінімальну, максимальну температуру та середньорічну (округли до 1 знаку)

In [2]:
import numpy as np

# Твій код:
# 1. Створення та виведення масиву
temps = np.array([-5, -4, 2, 10, 17, 21, 23, 22, 16, 9, 2, -3])

# 2. Виведення масиву
print("Масив temps:", temps)

# 3. Виведення вимірів
print("Кількість вимірів (ndim):", temps.ndim)
print("Форма (shape):", temps.shape)
print("Кількість елементів (size):", temps.size)
print("Тип даних (dtype):", temps.dtype)

# Виведи мінімальну, максимальну температуру та середньорічну (округли до 1 знаку)
print("Мінімальна температура:", temps.min(), "°C")
print("Максимальна температура:", temps.max(), "°C")
print("Середньорічна температура:", round(temps.mean(), 1), "°C")

Масив temps: [-5 -4  2 10 17 21 23 22 16  9  2 -3]
Кількість вимірів (ndim): 1
Форма (shape): (12,)
Кількість елементів (size): 12
Тип даних (dtype): int64
Мінімальна температура: -5 °C
Максимальна температура: 23 °C
Середньорічна температура: 9.2 °C


### ✏️ Завдання 1.2

Створи таблицю планових продажів для 3 менеджерів на 4 квартали.

1. Створи матрицю `plan` розміром **3×4**, заповнену значенням `50` (тис. грн) — використай `np.full()`
2. Виведи матрицю
3. Виведи її форму та загальну кількість елементів
4. Створи другу матрицю `bonus` розміром **3×4** із нулів — менеджери ще не отримали бонусів
5. Виведи суму `plan + bonus` і переконайся що вона рівна `plan`

In [3]:
# Твій код:
# 1. Створи матрицю plan розміром 3×4, заповнену значенням 50 (тис. грн) — використай np.full()
plan = np.full((3, 4), 50)

# 2. Виведи матрицю
print(plan)

# 3. Виведи її форму та загальну кількість елементів
print(f"Форма матриці: {plan.shape}")
print(f"Загальна кількість елементів: {plan.size}")

# 4. Створи другу матрицю bonus розміром 3×4 із нулів — менеджери ще не отримали бонусів
bonus = np.zeros((3, 4), dtype=int)
print("Матриця bonus:")
print(bonus)

# 5. Виведи суму plan + bonus і переконайся що вона рівна plan
total = plan + bonus
print("Сума plan + bonus:")
print(total)

is_equal = np.array_equal(total, plan)
print(f"Чи рівна сума матриці plan?: {is_equal}")

[[50 50 50 50]
 [50 50 50 50]
 [50 50 50 50]]
Форма матриці: (3, 4)
Загальна кількість елементів: 12
Матриця bonus:
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
Сума plan + bonus:
[[50 50 50 50]
 [50 50 50 50]
 [50 50 50 50]]
Чи рівна сума матриці plan?: True


---
## Розділ 2 — Індексація та зрізи

> **Що повторюємо:** індексація 1D і 2D масивів, зрізи `[start:stop:step]`,
> вибір рядків та стовпців матриці

### ✏️ Завдання 2.1

Є масив денних продажів магазину за 2 тижні (14 днів):

```python
sales = np.array([320, 415, 290, 480, 350, 620, 580,
                  310, 440, 305, 510, 370, 650, 595])
```

Виконай такі вибірки **без циклів**, лише через зрізи:
1. Продажі першого тижня (дні 1–7)
2. Продажі другого тижня (дні 8–14)
3. Продажі у вихідні: 6-й, 7-й, 13-й, 14-й день — використай індексацію списком `[[5,6,12,13]]`
4. Продажі через день, починаючи з першого (непарні дні: 1, 3, 5...)
5. Масив у зворотному порядку

In [4]:
sales = np.array([320, 415, 290, 480, 350, 620, 580,
                  310, 440, 305, 510, 370, 650, 595])

# Твій код:
# 1. Продажі першого тижня (дні 1–7)
first_week = sales[0:7]

# 2. Продажі другого тижня (дні 8–14)
second_week = sales[7:]

# 3. Продажі у вихідні: 6-й, 7-й, 13-й, 14-й день — використай індексацію списком [[5,6,12,13]]
weekends = sales[[5, 6, 12, 13]]

# 4. Продажі через день, починаючи з першого (непарні дні: 1, 3, 5...)
odd_days = sales[::2]

# 5. Масив у зворотному порядку
reversed_sales = sales[::-1]

print("1. Перший тиждень:               ", first_week)
print("2. Другий тиждень:               ", second_week)
print("3. Вихідні дні:                  ", weekends)
print("4. Через день (непарні дні):     ", odd_days)
print("5. Масив у зворотному порядку:   ", reversed_sales)



1. Перший тиждень:                [320 415 290 480 350 620 580]
2. Другий тиждень:                [310 440 305 510 370 650 595]
3. Вихідні дні:                   [620 580 650 595]
4. Через день (непарні дні):      [320 290 350 580 440 510 650]
5. Масив у зворотному порядку:    [595 650 370 510 305 440 310 580 620 350 480 290 415 320]


### ✏️ Завдання 2.2

Є матриця оцінок студентів: **4 студенти × 5 предметів**.

```python
grades = np.array([
    [85, 72, 91, 78, 88],   # Олена
    [63, 88, 74, 95, 70],   # Максим
    [90, 65, 82, 70, 94],   # Аня
    [75, 80, 68, 85, 79],   # Богдан
])
```

1. Виведи всі оцінки Олени (перший рядок)
2. Виведи оцінки всіх студентів з 3-го предмету (третій стовпець)
3. Виведи підматрицю: оцінки Максима та Ані з предметів 2–4 (рядки 1–2, стовпці 1–3)
4. Виведи оцінки останнього студента з останнього предмету

In [5]:
grades = np.array([
    [85, 72, 91, 78, 88],
    [63, 88, 74, 95, 70],
    [90, 65, 82, 70, 94],
    [75, 80, 68, 85, 79],
])

# Твій код:
# 1. Виведи всі оцінки Олени (перший рядок)
olena_grades = grades[0, :]

# 2. Виведи оцінки всіх студентів з 3-го предмету (третій стовпець)
subject_3_grades = grades[:, 2]

# 3. Виведи підматрицю: оцінки Максима та Ані з предметів 2–4 (рядки 1–2, стовпці 1–3)
submatrix = grades[1:3, 1:4]

# 4. Виведи оцінки останнього студента з останнього предмету
last_grade = grades[-1, -1]

print("1. Оцінки Олени: \n", olena_grades)
print("\n2. Оцінки всіх з 3-го предмету: \n", subject_3_grades)
print("\n3. Підматриця (Максим та Аня, предмети 2-4): \n", submatrix)
print("\n4. Оцінка останнього студента з останнього предмету: \n", last_grade)

1. Оцінки Олени: 
 [85 72 91 78 88]

2. Оцінки всіх з 3-го предмету: 
 [91 74 82 68]

3. Підматриця (Максим та Аня, предмети 2-4): 
 [[88 74 95]
 [65 82 70]]

4. Оцінка останнього студента з останнього предмету: 
 79


---
## Розділ 3 — Математичні операції та векторизація

> **Що повторюємо:** арифметика з масивами, `np.sqrt()`, `np.round()`,
> агрегатні функції `.sum()`, `.mean()`, `.std()`, `.min()`, `.max()`, `np.median()`

### ✏️ Завдання 3.1

Є масив цін товарів у доларах. Виконай **без циклів**:

```python
prices_usd = np.array([15.99, 42.50, 8.00, 125.00, 33.75, 67.20, 9.99])
```

1. Переведи ціни в гривні (курс: **1 USD = 41.5 UAH**), результат округли до 2 знаків
2. Нарахуй ПДВ 20% — помнож гривневі ціни на 1.2, округли до 2 знаків
3. Знайди: мінімальну, максимальну, середню ціну з ПДВ
4. Знайди суму всіх товарів з ПДВ — це загальна вартість кошика
5. Виведи результати з поясненнями

In [6]:
prices_usd = np.array([15.99, 42.50, 8.00, 125.00, 33.75, 67.20, 9.99])

# Твій код:
# 1. Переведи ціни в гривні (курс: 1 USD = 41.5 UAH), результат округли до 2 знаків
prices_uah = np.round(prices_usd * 41.5, 2)

# 2. Нарахуй ПДВ 20% — помнож гривневі ціни на 1.2, округли до 2 знаків
prices_vat = np.round(prices_uah * 1.2, 2)

# 3. Знайди: мінімальну, максимальну, середню ціну з ПДВ
min_price = np.min(prices_vat)
max_price = np.max(prices_vat)
mean_price = np.round(np.mean(prices_vat), 2)

# 4. Знайди суму всіх товарів з ПДВ — це загальна вартість кошика
total_sum = np.round(np.sum(prices_vat), 2)

# 5. Виведи результати з поясненнями
print("1. Ціни в гривнях (без ПДВ):")
print(prices_uah)

print("\n2. Ціни в гривнях (з ПДВ 20%):")
print(prices_vat)

print("\n3. Метрики для цін з ПДВ:")
print(f"   - Мінімальна ціна: {min_price} грн")
print(f"   - Максимальна ціна: {max_price} грн")
print(f"   - Середня ціна товару: {mean_price} грн")

print("\n4. Загальна вартість кошика:")
print(f"   - Разом до сплати: {total_sum} грн")

1. Ціни в гривнях (без ПДВ):
[ 663.58 1763.75  332.   5187.5  1400.62 2788.8   414.58]

2. Ціни в гривнях (з ПДВ 20%):
[ 796.3  2116.5   398.4  6225.   1680.74 3346.56  497.5 ]

3. Метрики для цін з ПДВ:
   - Мінімальна ціна: 398.4 грн
   - Максимальна ціна: 6225.0 грн
   - Середня ціна товару: 2151.57 грн

4. Загальна вартість кошика:
   - Разом до сплати: 15061.0 грн


### ✏️ Завдання 3.2

Є дані про кількість товарів на складі та їх собівартість.
Виконай **без циклів**:

```python
quantity  = np.array([120, 45, 300, 18, 75, 200, 60])
cost_each = np.array([250, 1800, 45, 9500, 380, 120, 750])
names     = ['Кабель', 'Клавіатура', 'Зошит', 'Монітор',
             'Мишка', 'Ручка', 'Навушники']
```

1. Порахуй загальну вартість кожного товару на складі (`quantity * cost_each`)
2. Знайди загальну вартість всього складу
3. Знайди товар з найбільшою сумарною вартістю — використай `np.argmax()`
4. Знайди товар з найменшою сумарною вартістю — `np.argmin()`
5. Виведи середню вартість одного найменування на складі

In [16]:
quantity  = np.array([120, 45, 300, 18, 75, 200, 60])
cost_each = np.array([250, 1800, 45, 9500, 380, 120, 750])
names     = ['Кабель', 'Клавіатура', 'Зошит', 'Монітор',
             'Мишка', 'Ручка', 'Навушники']

# Твій код:
# 1. Порахуй загальну вартість кожного товару на складі (quantity * cost_each)
total_per_item = quantity * cost_each

# 2. Знайди загальну вартість всього складу
warehouse_total = np.sum(total_per_item)

# 3. Знайди товар з найбільшою сумарною вартістю — використай np.argmax()
max_index = np.argmax(total_per_item)
max_item_name = names[max_index]
max_item_value = total_per_item[max_index]

# 4. Знайди товар з найменшою сумарною вартістю — np.argmin()
min_index = np.argmin(total_per_item)
min_item_name = names[min_index]
min_item_value = total_per_item[min_index]

# 5. Виведи середню вартість одного найменування на складі
average_value = np.mean(total_per_item)

print("1. Сумарна вартість кожного товару на складі:")
for name, total in zip(names, total_per_item):
    print(f"   - {name}: {total:,} грн")

print(f"\n2. Загальна вартість всього складу: {warehouse_total:,} грн")

print(f"\n3. Товар з найбільшою вартістю: {max_item_name} ({max_item_value:,} грн)")

print(f"\n4. Товар з найменшою вартістю: {min_item_name} ({min_item_value:,} грн)")

print(f"\n5. Середня вартість одного найменування: {average_value:,.2f} грн")

1. Сумарна вартість кожного товару на складі:
   - Кабель: 30,000 грн
   - Клавіатура: 81,000 грн
   - Зошит: 13,500 грн
   - Монітор: 171,000 грн
   - Мишка: 28,500 грн
   - Ручка: 24,000 грн
   - Навушники: 45,000 грн

2. Загальна вартість всього складу: 393,000 грн

3. Товар з найбільшою вартістю: Монітор (171,000 грн)

4. Товар з найменшою вартістю: Зошит (13,500 грн)

5. Середня вартість одного найменування: 56,142.86 грн


---
## Розділ 4 — Булеве маскування і фільтрація

> **Що повторюємо:** булеві маски, фільтрація `arr[mask]`,
> `np.where()`, `.sum()` для підрахунку True

### ✏️ Завдання 4.1

Є масив часу виконання замовлень у хвилинах (норма — до 30 хв):

```python
delivery_time = np.array([22, 35, 28, 41, 19, 55, 27, 33, 24, 48,
                           31, 26, 52, 18, 29, 38, 23, 44, 20, 36])
```

1. Знайди всі замовлення, виконані **вчасно** (≤ 30 хв)
2. Знайди всі **запізнілі** замовлення (> 30 хв)
3. Порахуй кількість вчасних і запізнілих
4. Знайди відсоток запізнілих замовлень (округли до 1 знаку)
5. Яка середня затримка серед запізнілих замовлень?

In [17]:
delivery_time = np.array([22, 35, 28, 41, 19, 55, 27, 33, 24, 48,
                           31, 26, 52, 18, 29, 38, 23, 44, 20, 36])

# Твій код:
# 1. Знайди всі замовлення, виконані вчасно (≤ 30 хв)
on_time_mask = delivery_time <= 30
on_time_orders = delivery_time[on_time_mask]

# 2. Знайди всі запізнілі замовлення (> 30 хв)
delayed_mask = delivery_time > 30
delayed_orders = delivery_time[delayed_mask]

# 3. Порахуй кількість вчасних і запізнілих
count_on_time = len(on_time_orders)
count_delayed = len(delayed_orders)
total_orders = len(delivery_time)

# 4. Знайди відсоток запізнілих замовлень (округли до 1 знаку)
pct_delayed = np.round((count_delayed / total_orders) * 100, 1)

# 5. Яка середня затримка серед запізнілих замовлень?
delays = delayed_orders - 30
average_delay = np.round(np.mean(delays), 1)

print("1. Замовлення, виконані вчасно (≤ 30 хв):")
print(f"   {on_time_orders}")

print("\n2. Запізнілі замовлення (> 30 хв):")
print(f"   {delayed_orders}")

print("\n3. Статистика кількості:")
print(f"   - Вчасних замовлень: {count_on_time} шт.")
print(f"   - Запізнілих замовлень: {count_delayed} шт.")

print("\n4. Відсоток запізнілих замовлень:")
print(f"   - {pct_delayed}% від усіх замовлень")

print("\n5. Середня затримка серед запізнілих замовлень:")
print(f"   - {average_delay} хв. (на стільки в середньому перетримували кожне проблемне замовлення)")


1. Замовлення, виконані вчасно (≤ 30 хв):
   [22 28 19 27 24 26 18 29 23 20]

2. Запізнілі замовлення (> 30 хв):
   [35 41 55 33 48 31 52 38 44 36]

3. Статистика кількості:
   - Вчасних замовлень: 10 шт.
   - Запізнілих замовлень: 10 шт.

4. Відсоток запізнілих замовлень:
   - 50.0% від усіх замовлень

5. Середня затримка серед запізнілих замовлень:
   - 11.3 хв. (на стільки в середньому перетримували кожне проблемне замовлення)


### ✏️ Завдання 4.2

Є масив щоденних продажів за місяць. Використай `np.where()`:

```python
np.random.seed(42)
daily = np.random.randint(100, 900, size=30)
```

1. Знайди дні з продажами **вище середнього** за місяць
2. Порахуй скільки таких днів
3. За допомогою `np.where()` створи масив `status`:
   - `'Гарний день'` — якщо продажі вище середнього
   - `'Звичайний день'` — якщо нижче або рівно
4. Виведи перші 10 днів: продажі та їх статус поряд

In [18]:
np.random.seed(42)
daily = np.random.randint(100, 900, size=30)

# Твій код:
monthly_average = np.mean(daily)

# 1. Знайди дні з продажами вище середнього за місяць
good_days_indices = np.where(daily > monthly_average)[0] + 1

# 2. Порахуй скільки таких днів
good_days_count = len(good_days_indices)

# 3. За допомогою np.where() створи масив status:
          # - 'Гарний день' — якщо продажі вище середнього
          # - 'Звичайний день' — якщо нижче або рівно
status = np.where(daily > monthly_average, 'Гарний день', 'Звичайний день')

# 4. Виведи перші 10 днів: продажі та їх статус поряд
print(f"Середні продажі за місяць: {monthly_average:.1f} грн\n")

print("1. Дні з продажами вище середнього (номери днів):")
print(good_days_indices)

print(f"\n2. Кількість днів з продажами вище середнього: {good_days_count} днів")

print("\n3. Результати за перші 10 днів (продажі та статус):")
for i in range(10):
    print(f"   День {i+1:2d}: {daily[i]} грн — {status[i]}")


Середні продажі за місяць: 434.2 грн

1. Дні з продажами вище середнього (номери днів):
[ 2  6  8 10 13 15 17 19 21 22 23 24 25 29]

2. Кількість днів з продажами вище середнього: 14 днів

3. Результати за перші 10 днів (продажі та статус):
   День  1: 202 грн — Звичайний день
   День  2: 535 грн — Гарний день
   День  3: 370 грн — Звичайний день
   День  4: 206 грн — Звичайний день
   День  5: 171 грн — Звичайний день
   День  6: 800 грн — Гарний день
   День  7: 120 грн — Звичайний день
   День  8: 714 грн — Гарний день
   День  9: 221 грн — Звичайний день
   День 10: 566 грн — Гарний день


---
## Розділ 5 — reshape та сортування

> **Що повторюємо:** `.reshape()`, `.flatten()`, `np.sort()`, `np.argsort()`

### ✏️ Завдання 5.1

Є 1D масив з 24 показників продажів (по годинах за добу):

```python
hourly = np.array([12, 8, 5, 3, 4, 9, 18, 35, 52, 61, 58, 64,
                   70, 67, 55, 48, 53, 62, 74, 68, 45, 30, 22, 15])
```

1. Перетвори масив у матрицю **6×4** (6 блоків по 4 години) і виведи
2. Знайди суму продажів у кожному 4-годинному блоці (по рядках)
3. Відсортуй вихідний 1D масив за **зростанням** і виведи
4. Знайди **індекси** годин відсортованих за зростанням продажів — `np.argsort()`
5. Виведи топ-3 найпродуктивніших години (їхні номери, рахуючи з 0)

In [22]:
hourly = np.array([12, 8, 5, 3, 4, 9, 18, 35, 52, 61, 58, 64,
                   70, 67, 55, 48, 53, 62, 74, 68, 45, 30, 22, 15])

# Твій код:
# 1. Перетвори масив у матрицю 6×4 (6 блоків по 4 години) і виведи
matrix_6x4 = hourly.reshape(6, 4)

print(matrix_6x4)
# 2. Знайди суму продажів у кожному 4-годинному блоці (по рядках)
block_sums = np.sum(matrix_6x4, axis=1)

# 3. Відсортуй вихідний 1D масив за зростанням і виведи
sorted_hourly = np.sort(hourly)

# 4. Знайди індекси годин відсортованих за зростанням продажів — np.argsort()
sorted_indices = np.argsort(hourly)

# 5. Виведи топ-3 найпродуктивніших години (їхні номери, рахуючи з 0)
top_3_hours = sorted_indices[:-4:-1]

print("1. Матриця 6х4 (6 блоків по 4 години):")
print(matrix_6x4)

print("\n2. Сума продажів у кожному 4-годинному блоці:")
print(block_sums)

print("\n3. Вихідний масив, відсортований за зростанням:")
print(sorted_hourly)

print("\n4. Індекси годин, відсортовані за зростанням продажів:")
print(sorted_indices)

print("\n5. Топ-3 найпродуктивніших години (номери годин з 0):")
print(top_3_hours)

[[12  8  5  3]
 [ 4  9 18 35]
 [52 61 58 64]
 [70 67 55 48]
 [53 62 74 68]
 [45 30 22 15]]
1. Матриця 6х4 (6 блоків по 4 години):
[[12  8  5  3]
 [ 4  9 18 35]
 [52 61 58 64]
 [70 67 55 48]
 [53 62 74 68]
 [45 30 22 15]]

2. Сума продажів у кожному 4-годинному блоці:
[ 28  66 235 240 257 112]

3. Вихідний масив, відсортований за зростанням:
[ 3  4  5  8  9 12 15 18 22 30 35 45 48 52 53 55 58 61 62 64 67 68 70 74]

4. Індекси годин, відсортовані за зростанням продажів:
[ 3  4  2  1  5  0 23  6 22 21  7 20 15  8 16 14 10  9 17 11 13 19 12 18]

5. Топ-3 найпродуктивніших години (номери годин з 0):
[18 12 19]


---
## Розділ 6 — Генерація випадкових чисел

> **Що повторюємо:** `np.random.seed()`, `np.random.randint()`,
> `np.random.normal()`, `np.random.choice()`

### ✏️ Завдання 6.1

Змоделюй результати маркетингового опитування 50 клієнтів.

1. Встанови `np.random.seed(99)`
2. Згенеруй масив `ages` — вік 50 клієнтів: цілі числа від 18 до 65
3. Згенеруй масив `scores` — оцінки задоволеності (нормальний розподіл, середнє=7, σ=1.5), округли до 1 знаку
4. Обріж `scores` так щоб значення були від 1 до 10 — `np.clip(arr, 1, 10)`
5. Виведи:
   - середній вік клієнтів
   - середню оцінку задоволеності
   - кількість клієнтів з оцінкою >= 8 («задоволені»)
   - відсоток задоволених

In [23]:
# Твій код:
# 1. Встанови np.random.seed(99)
np.random.seed(99)

# 2. Згенеруй масив ages — вік 50 клієнтів: цілі числа від 18 до 65
ages = np.random.randint(18, 66, size=50)

# 3. Згенеруй масив scores — оцінки задоволеності (нормальний розподіл, середнє=7, σ=1.5), округли до 1 знаку
raw_scores = np.random.normal(loc=7.0, scale=1.5, size=50)
scores_rounded = np.round(raw_scores, 1)

# 4. Обріж scores так щоб значення були від 1 до 10 — np.clip(arr, 1, 10)
scores = np.clip(scores_rounded, 1.0, 10.0)

# 5. Виведи:
     # середній вік клієнтів
     # середню оцінку задоволеності
     # кількість клієнтів з оцінкою >= 8 («задоволені»)
     # відсоток задоволених

average_age = np.mean(ages)
average_score = np.mean(scores)
satisfied_mask = scores >= 8.0
satisfied_count = np.sum(satisfied_mask)
satisfied_percentage = (satisfied_count / len(scores)) * 100


print("--- РЕЗУЛЬТАТИ МАРКЕТИНГОВОГО ОПИТУВАННЯ ---")
print(f"1. Середній вік опитаних клієнтів:      {average_age:.1f} років")
print(f"2. Середня оцінка задоволеності:        {average_score:.2f} з 10")
print(f"3. Кількість задоволених клієнтів (≥8): {satisfied_count} осіб")
print(f"4. Відсоток задоволених клієнтів:       {satisfied_percentage:.1f}%")


--- РЕЗУЛЬТАТИ МАРКЕТИНГОВОГО ОПИТУВАННЯ ---
1. Середній вік опитаних клієнтів:      41.8 років
2. Середня оцінка задоволеності:        6.87 з 10
3. Кількість задоволених клієнтів (≥8): 10 осіб
4. Відсоток задоволених клієнтів:       20.0%


---
## 🏆 Фінальний проєкт — Аналіз даних магазину

> **Використовуємо все з тьюторіалу разом**

Ти аналітик даних невеликого магазину електроніки.
Тобі передали масив продажів за 8 тижнів (56 днів).

Виконай повний аналіз та дай відповіді на запитання керівника.

In [12]:
# Дані — не змінюй цю клітинку
np.random.seed(2024)
base = np.random.randint(200, 800, 56)

# Вихідні продаються краще
weekend_boost = np.array([1 if i % 7 in [5, 6] else 0 for i in range(56)])
sales_56 = (base + weekend_boost * np.random.randint(100, 300, 56)).astype(int)

print('Дані отримано. Масив sales_56 готовий до аналізу.')
print(f'Елементів: {sales_56.size}, форма: {sales_56.shape}')


Дані отримано. Масив sales_56 готовий до аналізу.
Елементів: 56, форма: (56,)


### Запитання 1 — Загальна статистика (Розділ 1, 3)
Виведи:
- Загальна виручка за 56 днів
- Середньоденна виручка (округли до 2 знаків)
- Мінімальний та максимальний денний продаж
- Стандартне відхилення (наскільки продажі «скачуть»)

In [26]:
# Твій код:
total_revenue = np.sum(sales_56)
mean_revenue = np.mean(sales_56)
min_sale = np.min(sales_56)
max_sale = np.max(sales_56)
std_dev = np.std(sales_56)
print(f"• Загальна виручка за 56 днів:        {total_revenue:,} грн")
print(f"• Середньоденна виручка:              {mean_revenue:.2f} грн")
print(f"• Мінімальний денний продаж:          {min_sale} грн")
print(f"• Максимальний денний продаж:         {max_sale} грн")
print(f"• Стандартне відхилення (волатильність): {std_dev:.2f} грн")

• Загальна виручка за 56 днів:        31,819 грн
• Середньоденна виручка:              568.20 грн
• Мінімальний денний продаж:          222 грн
• Максимальний денний продаж:         1072 грн
• Стандартне відхилення (волатильність): 195.52 грн


### Запитання 2 — Тижневий аналіз (Розділ 5)
1. Перетвори `sales_56` у матрицю **8×7** (8 тижнів по 7 днів)
2. Знайди виручку кожного тижня (сума по рядках)
3. Знайди найкращий тиждень і виведи його номер (рахуючи з 1) та суму
4. Знайди середньоденну виручку по кожному дню тижня (середнє по стовпцях)
5. Виведи який день тижня в середньому найприбутковіший (0=Пн, 6=Нд)

In [29]:
# Твій код:
matrix_8x7 = sales_56.reshape(8, 7)
weekly_revenue = np.sum(matrix_8x7, axis=1)

best_week_idx = np.argmax(weekly_revenue)
best_week_num = best_week_idx + 1
best_week_sum = weekly_revenue[best_week_idx]

weekday_means = np.mean(matrix_8x7, axis=0)
best_day_idx = np.argmax(weekday_means)

print("• Виручка по тижнях:")
for w, rev in enumerate(weekly_revenue, 1):
    print(f"  - Тиждень {w}: {rev:,} грн")
print(f"• Найкращий тиждень: №{best_week_num} з виручкою {best_week_sum:,} грн")
print("• Середня виручка по днях тижня (0=Пн, 6=Нд):")
days_names = ["Пн", "Вт", "Ср", "Чт", "Пт", "Сб", "Нд"]
for d_idx, d_mean in enumerate(weekday_means):
    print(f"  - {days_names[d_idx]} (Індекс {d_idx}): {d_mean:.2f} грн")
print(f"• Найприбутковіший день тижня: {days_names[best_day_idx]} (індекс {best_day_idx})")

• Виручка по тижнях:
  - Тиждень 1: 4,555 грн
  - Тиждень 2: 3,921 грн
  - Тиждень 3: 3,563 грн
  - Тиждень 4: 3,546 грн
  - Тиждень 5: 5,036 грн
  - Тиждень 6: 3,300 грн
  - Тиждень 7: 4,228 грн
  - Тиждень 8: 3,670 грн
• Найкращий тиждень: №5 з виручкою 5,036 грн
• Середня виручка по днях тижня (0=Пн, 6=Нд):
  - Пн (Індекс 0): 520.38 грн
  - Вт (Індекс 1): 455.50 грн
  - Ср (Індекс 2): 565.88 грн
  - Чт (Індекс 3): 607.75 грн
  - Пт (Індекс 4): 463.75 грн
  - Сб (Індекс 5): 629.75 грн
  - Нд (Індекс 6): 734.38 грн
• Найприбутковіший день тижня: Нд (індекс 6)


### Запитання 3 — Фільтрація та маскування (Розділ 4)
1. Знайди кількість **«слабких» днів** — продажі нижче 400 грн
2. Знайди кількість **«сильних» днів** — продажі вище 700 грн
3. Яка середня виручка у слабкі дні і яка у сильні?
4. Створи масив `labels` за допомогою `np.where()`:
   - `'Слабкий'` якщо < 400
   - `'Сильний'` якщо > 700
   - `'Нормальний'` в решті випадків (підказка: вкладений `np.where`)
5. Виведи перші 14 днів: продажі та їх мітки

In [30]:
# Твій код:
weak_mask = sales_56 < 400
strong_mask = sales_56 > 700

weak_count = np.sum(weak_mask)
strong_count = np.sum(strong_mask)

weak_mean = np.mean(sales_56[weak_mask]) if weak_count > 0 else 0
strong_mean = np.mean(sales_56[strong_mask]) if strong_count > 0 else 0

labels = np.where(sales_56 < 400, 'Слабкий',
                 np.where(sales_56 > 700, 'Сильний', 'Нормальний'))

print(f"• Кількість «слабких» днів (<400 грн): {weak_count} днів")
print(f"• Кількість «сильних» днів (>700 грн): {strong_count} днів")
print(f"• Середня виручка у слабкі дні:        {weak_mean:.2f} грн")
print(f"• Середня виручка у сильні дні:        {strong_mean:.2f} грн")


• Кількість «слабких» днів (<400 грн): 12 днів
• Кількість «сильних» днів (>700 грн): 19 днів
• Середня виручка у слабкі дні:        302.00 грн
• Середня виручка у сильні дні:        785.16 грн


---
## ✅ Підсумок

| Розділ | Завдання | Балів | Виконано |
|--------|----------|-------|----------|
| 1 — Масиви ndarray | 1.1, 1.2 | 2 | ☐ |
| 2 — Індексація та зрізи | 2.1, 2.2 | 2 | ☐ |
| 3 — Математичні операції | 3.1, 3.2 | 2 | ☐ |
| 4 — Булеве маскування | 4.1, 4.2 | 2 | ☐ |
| 5 — reshape та сортування | 5.1 | 1 | ☐ |
| 6 — Генерація випадкових | 6.1 | 1 | ☐ |
| 🏆 Фінальний проєкт | Питання 1–3 | 3 | ☐ |
| **Разом** | | **13** | |
